### ISSUE TITLE
Operator matching '>=' vs '>'

### ISSUE THREAD

**Issue by malcolm-p** [davedufresne/SwiftParsec#20]
Hi, Thanks for a great library!

I am porting a parser from FParsec to SwiftParsec and it's gone pretty well. One difference in behaviour is operator matching. I would like to parse '>=' and if that fails '>', but the operator behaviour doesn't allow this e.g when constructing the OperatorTable: 

```
[
        binary(">=", function: { Expr.Comparison($0, .Ge, $1) }, assoc: .none),
        binary("<=", function: { Expr.Comparison($0, .Le, $1) }, assoc: .none),
        binary("<", function: { Expr.Comparison($0, .Lt, $1) }, assoc: .none),
        binary(">", function: { Expr.Comparison($0, .Gt, $1) }, assoc: .none)
],
```

So for `var1 > 3` FParsec will attempt '>=' and then succeed on '>'. Is there a way to replicate this behaviour?

Thanks again.

**Comment by davedufresne** [comment]
Hi Malcom,

Would the `alternative` or its equivalent `<|>` work for your purpose? There is also the `attempt` parser for lookahead. Look at the comments in 'Parsec.swift` file.
