### ISSUE TITLE
Latest GitHub release does not include fix for Xcode 12.5

### ISSUE THREAD

**Issue by MarcoEidinger** [davedufresne/SwiftParsec#23]
Hi,

I am using Swift Package Manager and I added this package with its latest version `4.0.0`. I am using Xcode 12.5 and I got a compiler error. Unfortunately, the existing fix https://github.com/davedufresne/SwiftParsec/commit/e8d092de0c206decadfbd15c4b5a82209594bed0 (fix compiler error in Xcode 12.5) is not part of release `4.0.0` and I have to refer to the `master` branch. Would be great if a release `4.0.1` would be tagged including this important fix.

Kind regards,
Marco

**Comment by davedufresne** [comment]
Hi,

I just created a new release with the fix you need.

Regards

**Comment by MarcoEidinger** [comment]
Thank you!
