### ISSUE TITLE
Getting the source position out?

### ISSUE THREAD

**Issue by chriseidhof** [davedufresne/SwiftParsec#3]
Hey @davedufresne ! Awesome project. We're thinking of using it for a project. The code looks really solid.

I want to get the source position out, so that we can parse into an AST that is annotated with the source positions. Using the public API, this is currently not possible, right? Would you mind adding this if I create a PR?

**Comment by davedufresne** [comment]
Hi Chris,

This is a good idea, I forgot to implement this feature. It would go in the 2.0-dev branch.

Thanks.

**Comment by davedufresne** [comment]
The feature is now in the 2.0-dev branch. See `Parsec.sourcePosition` or `GenericParser.sourcePosition`.
