### ISSUE TITLE
Building on Ubuntu

### ISSUE THREAD

**Issue by hkgumbs** [davedufresne/SwiftParsec#7]
Greetings,

I am having trouble building this library on Ubuntu 16.04 (Swift 3.0.2). The issue may be related to a compiler bug, but I decided to post it here in case you thought otherwise. The code I'll refer to below is that in https://github.com/hkgumbs/SwiftParsec/master, which has only compatibility changes. I think the quickest way to play with Ubuntu 16.04 would be use Docker: `docker run -it -v $PWD:/code -w /code swiftdocker/swift bash`.

## Sources

```
swift build
...
	Cross-reference to module 'SwiftParsec'
	... TokenParser
	... in an extension in module 'SwiftParsec'
	... identifier
	... with type GenericParser<String, τ_0_0.UserState, String>
```

I found a [SO post](http://stackoverflow.com/questions/40632924/segmentation-fault-11-cross-reference-to-module) that described similar symptoms, and the recommendation there is to use the  `-whole-module-optimization` flag.

```
swift build -Xswiftc -whole-module-optimization -c release
```

The `release` configuration is what ultimately tells the `swift-build-tool` to look elsewhere for dependency mappings ([Source](https://github.com/apple/swift-package-manager/blob/1086c87a0351fb7c81d39ec3dd911c439bf14970/Sources/Build/ToolProtocol.swift#L87)). Otherwise, `swift build` fails with `unable to open dependencies file '/code/.build/debug/SwiftParsec.build/CharacterMembership.d'`.

## Tests

These flags don't port as nicely to tests. I think this is the major issue since I want to verify that the changes and optimizations are not affecting the behavior of the library. The root of the problem seems to be that I cannot force `-c release` in test builds. One workaround is run `swift test -Xswiftc -whole-module-optimization` then manually modify `.build/debug.yaml`:

```diff
--- a/.build/debug.yaml
+++ b/.build/debug.yaml
@@ -22 +22 @@ commands:
-    enable-whole-module-optimization: false
+    enable-whole-module-optimization: true
@@ -38 +38 @@ commands:
-    enable-whole-module-optimization: false
+    enable-whole-module-optimization: true
``` 

Once you make those changes, you can run the `swift-build-tool` manually, and it will compile the tests. However, you'll still see a problem at link time. The output is mostly gibberish - this is the farthest I've gotten:

```
/usr/bin/swift-build-tool -f /code/.build/debug.yaml test
...
```

------

Like I mentioned at the start, this doesn't seem to be an issue with your project specifically, but I thought I'd bring it up just in case you had any ideas.

Cheers!

**Comment by davedufresne** [comment]
Hi,

Thank you for your interest in SwiftParsec. I didn't work on porting the library to linux yet. But I'm planning to do so when I'll have more time. If you manage to do so, feel free to contribute.

Thank you for your research.

**Comment by hkgumbs** [comment]
@davedufresne I'm not sure how to contact you outside of GitHub, but I've submitted a PR that implements this.

**Comment by davedufresne** [comment]
@hkgumbs you can find my email address in one of my commits. I will try to start code reviewing this weekend. Thanks for your work.

**Comment by davedufresne** [comment]
Great job! Many thanks. I only left comments about minor styling issues. As soon as you fix them I'll release a new version of the library.
