### ISSUE TITLE
testRecursive possibly fails due to wrong associativity

### ISSUE THREAD

**Issue by DressTheMonkey** [davedufresne/SwiftParsec#9]
I've been studying the testRecursive method in CombinatorParsersTests.swift because I'm trying to understand how the whole recursive thing works.  In order to test my understanding, I was playing around with different input and have discovered a test failure.

If I change the matching and expected definitions to this:

```swift
        let matching = ["3-(1+2)", "3-1+2", "3-(1-(3+1))"]
        let expected = [3-(1+2), 3-1+2, 3-(1-(3+1))]
```

It fails with the message, `CombinatorParsersTests.swift:1114: error: -[SwiftParsecTests.CombinatorTests testRecursive] : XCTAssertEqual failed: ("4") is not equal to ("0")`

Whether or not this is an actual failure depends on the intended associativity of the operators, since that isn't stated anywhere, and the context leads me to believe Swift-like associativity is desired, I thought I would note it here; sorry if that is not what is intended.

I am also sorry I can't offer a fix, but to offer a fix would require my understanding recursive and that is the very reason I'm here looking at recursive! 🤷‍♂️

**Comment by davedufresne** [comment]
Hi,

This test was not intended to test associativity. In this simple test of an expression parser, all the operators are right-associative. If you would like to study exemples of expression parsers taking in account associativity, look at this file: https://github.com/davedufresne/SwiftParsec/blob/master/Sources/SwiftParsec/ExpressionParser.swift
